### ISSUE TITLE
Homeseite

### ISSUE THREAD

**Issue by MaxBergmann369** [MaxBergmann369/ProjectMatch#6]
- Beschreibung: Gestaltung und Entwicklung der Benutzeroberfläche für die Hauptseite nach dem Login, bei der man durch scrollen Projecte finden kann.
- Zeitaufwand: 10 Stunden
- Definition of Done:
  - Die Homeseite zeigt aktuelle Projekte korrekt an.
  - Die Navigation und das Scrollverhalten sind flüssig.
  - Alle Inhalte werden dynamisch geladen und aktualisiert.

**Comment by hoellerl** [comment]
closed in #38
